spring:
  datasource:
    main:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mariadb://smartstore.cwfapijmqt4o.ap-northeast-2.rds.amazonaws.com:3306/commerce
      username: admin
      password: DzWryUlpe5tAqNc0RjAs
      driver-class-name: org.mariadb.jdbc.Driver
      connectionTimeout: 10000
      validationTimeout: 1000
      maximum-pool-size: 10
      minimum-idle: 10
    readonly:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mariadb://smartstore.cwfapijmqt4o.ap-northeast-2.rds.amazonaws.com:3306/commerce
      username: admin
      password: DzWryUlpe5tAqNc0RjAs
      driver-class-name: org.mariadb.jdbc.Driver
      connectionTimeout: 10000
      validationTimeout: 1000
      maximum-pool-size: 10
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

smartstore:
  data:
    naver-data-lab:
      client-id: CBhLfVzN2Ype6luqClfq
      client-secret: h362wQE2hk
      url: https://openapi.naver.com/v1/datalab/shopping/categories