server:
  port: 8080

spring:
  application:
    name: smartstore-insight
  jpa:
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
